# Generated by Django 5.2.4 on 2025-07-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='professional',
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('SCHOOL', 'School'), ('PROFESSIONAL', 'Professional'), ('PERSONAL', 'Personal')], default='PERSONAL', max_length=20),
        ),
    ]
